# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Settings
title: Cloud Adventures
description: >- # this means to ignore newlines until "baseurl:"
  My problems and solutions to cloud integration, containerisation and devops
url: https://milkyware.github.io
repository: milkyware/milkyware.github.io

# Social Profile
github_username:  milkyware

# Build settings
# theme: jekyll-theme-clean-blog
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: dark
breadcrumbs: true
search: true
include:
  - _pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Site Author
author:
  name: Cameron Cowen
  avatar: "/images/bio-photo.jpg"
  bio: An integration developer focused on DevOps, APIs and containerisation in the cloud.
  location: UK

  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/milkyware
    - label: Website
      icon: fas fa-link
      url: https://milkyware.github.io

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/milkyware"
    - label: "Cloud icons created by Vectorslab - Flaticon"
      url: "https://www.flaticon.com/free-icons/cloud"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      show_date: true
      related: true
      toc: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
