name: spell check

on:
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main
    paths: 
      - _drafts
      - _posts
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: tbroadley/spellchecker-cli-action@v1
        name: Spell Check
        with:
          files: "**/*.md"
          language: en-GB
          quiet: true
